import {Platform, StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1 },
    header: { paddingHorizontal: 20, paddingBottom: 20, alignItems: 'center' },
    headerTitle: { color: '#93C5FD', fontSize: 14, fontWeight: '600', marginBottom: 10, textTransform: 'uppercase', letterSpacing: 1 },
    seletorMes: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
    botaoMes: { padding: 6 },
    botaoMesDesativado: { opacity: 0.35 },
    rotuloMes: { color: '#FFFFFF', fontSize: 16, fontWeight: '700', minWidth: 155, textAlign: 'center', textTransform: 'capitalize' },
    saldoText: { color: '#FFFFFF', fontSize: 40, fontWeight: 'bold', fontFamily: 'SpaceGrotesk_700Bold' },
    saldoLabel: { color: '#E0E7FF', fontSize: 14, marginTop: 5, marginBottom: 15 },
    resumoRow: { flexDirection: 'row', justifyContent: 'space-between', width: '100%', marginTop: 10, paddingHorizontal: 20 },
    resumoText: { color: '#93C5FD', fontSize: 12, fontWeight: 'bold' },
    scrollContainer: { flex: 1 },
    section: { padding: 20, paddingBottom: 0 },
    sectionTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 15 },
    sectionHeaderClickable: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
    badgeContagemFixas: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
    badgeContagemFixasTexto: { fontSize: 11, fontWeight: 'bold', fontFamily: 'SpaceGrotesk_600SemiBold' },
    graficoCard: { borderRadius: 16, padding: 20, borderWidth: 1, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 5, elevation: 2 },

    essencialCard: { padding: 16, borderRadius: 16, marginBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.03, shadowRadius: 5, elevation: 1 },
    essencialInfoRow: { flexDirection: 'row', alignItems: 'center' },
    essencialCardPago: { opacity: 0.6 },
    textoRiscado: { textDecorationLine: 'line-through', opacity: 0.7 },
    lojaText: { fontSize: 16, fontWeight: '700' },
    detalheText: { fontSize: 12, marginTop: 4 },
    valorFixo: { fontSize: 16, fontWeight: 'bold' },

    fab: { position: 'absolute', bottom: 20, right: 20, width: 65, height: 65, borderRadius: 35, justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 5, elevation: 8 },
    fabDesativado: { opacity: 0.4 },
    modalFundo: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 20 },
    modalContent: { borderRadius: 25, padding: 25, shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.2, shadowRadius: 10, elevation: 10 },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    modalTitle: { fontSize: 18, fontWeight: 'bold' },
    inputGrande: { fontSize: 40, fontWeight: 'bold', textAlign: 'center', marginBottom: 20, padding: 10 },
    inputNormal: { padding: 15, borderRadius: 12, fontSize: 16, marginBottom: 15 },
    pickerContainer: { borderRadius: 12, marginBottom: 15, overflow: 'hidden', paddingHorizontal: Platform.OS === 'android' ? 5 : 0 },
    labelPessoa: { fontSize: 14, fontWeight: 'bold', marginBottom: 10, marginTop: 5 },
    quemContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 25 },
    btnQuem: { flex: 1, minWidth: 100, padding: 14, borderRadius: 12, alignItems: 'center', borderWidth: 1, borderColor: 'transparent' },
    btnQuemTexto: { fontSize: 15, fontWeight: '600' },
    btnGuardar: { padding: 16, borderRadius: 12, alignItems: 'center' },
    btnGuardarTexto: { color: '#FFFFFF', fontSize: 18, fontWeight: 'bold' },

    pesquisaContainer: { marginBottom: 15, gap: 10 },
    inputPesquisaBox: { flexDirection: 'row', alignItems: 'center', borderRadius: 12, paddingHorizontal: 12, height: 44, borderWidth: 1 },
    inputPesquisa: { flex: 1, fontSize: 14 },
    chipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    chipPessoa: { paddingVertical: 6, paddingHorizontal: 14, borderRadius: 20 },
    chipTexto: { fontSize: 13, fontWeight: '600' },
    semResultadosBox: { alignItems: 'center', padding: 25, borderRadius: 16, marginTop: 10, gap: 8, borderWidth: 1 },
    semResultadosTexto: { fontSize: 14, textAlign: 'center' },
    btnLimparFiltros: { marginTop: 5, paddingVertical: 8, paddingHorizontal: 16, borderRadius: 10 },
    txtLimparFiltros: { fontWeight: 'bold', fontSize: 13 }
});