export const CATEGORIAS_DE_GASTO = [
    'Alimentação',
    'Restaurantes e Cafés',
    'Casa',
    'Streaming',
    'Saúde',
    'Transportes',
    'Lazer',
    'Compras',
    'Educação',
    'Subscrições',
    'Animais',
    'Presentes',
    'Outros',
];
